name: Pentaho PR Compliance
on:
  pull_request:
    branches:
      - "main"
      - "master"
      - "+([0-9])*(.+([0-9]))"
jobs:
  run-pr-compliance:
    name: Run PR Compliance Checks
    uses: pentaho/actions-common/.github/workflows/pr_compliance.yml@compliance
    secrets: inherit
